pdns:
  image: writl/pdns
  links:
  - "mysql:db"
  ports:
  - "53:53"
  - "53:53/udp"
  - "8080:80"
  environment:
  - PDNS_ALLOW_AXFR_IPS=127.0.0.1
mysql:
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD=ugs0irm9ek3wov6mud4e
  volumes:
  - /srv/docker/pdns-master/mysql/:/var/lib/mysql
